server:
  port: 8001

spring:
  application:
    name: service-dictionary
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        ephemeral: false
    sentinel:
      transport:
        dashboard: localhost:8858
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: '*'
            allowedMethods: '*'
            maxAge: 180
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/point_supply_station_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath*:mapper/*.xml


aliyun:
  sms:
    regionId: cn-hangzhou
    keyId: LTAI5t9iZe4hVXboJSYUwrgh
    keySecret: 7X4j4WvQ4LKFI6TYqI6HrrLwjgMQwW
    templateCode: SMS_278075084
    signName: 天然气点供站监控管理平台

